### ISSUE TITLE
logger not imported in yosys.py

### ISSUE THREAD

**Issue by DaveBerkeley** [olofk/edalize#189]
$ ./build.py
Traceback (most recent call last):
  File "./build.py", line 33, in <module>
    backend.configure()
  File "/tmp/edalize/edalize/edatool.py", line 112, in configure
    self.configure_main()
  File "/tmp/edalize/edalize/yosys.py", line 71, in configure_main
    logger.error("ERROR: arch is not defined.")
NameError: name 'logger' is not defined

Needs  :

import logging
logger = logging.getLogger(__name__)

Error occurs if arch is not defined. It could throw an Exception instead as the error is fatal?

**Comment by imphil** [comment]
Thanks for your bug report. Can you create a pull request to get your proposed change integrated? (The fix looks right to me.)
